[WARN ][20161209 00:58:02,054][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server 139.196.225.215/139.196.225.215:2181, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: 远程主机强迫关闭了一个现有的连接。
	at sun.nio.ch.SocketDispatcher.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:68)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[WARN ][20161209 00:58:02,059][AbstractServer:197]  [DUBBO] All clients has discontected from /192.168.31.211:20882. You can graceful shutdown now., dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 00:58:02,088][DubboProtocol$1:130]  [DUBBO] disconected from /192.168.31.211:57272,url:dubbo://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&channel.readonly.sent=true&codec=dubbo&dubbo=2.5.3&heartbeat=60000&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626, dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 00:58:02,157][ZkClient:711] zookeeper state changed (Disconnected)
[INFO ][20161209 10:28:14,730][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:24,021][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:26,094][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:26,094][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:27,833][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:27,833][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:29,538][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:29,552][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:31,273][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:31,273][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:33,091][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:33,091][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:34,661][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:34,661][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:36,278][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:36,278][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:37,810][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:37,820][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:39,541][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:39,551][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:41,465][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:41,465][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:43,336][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:43,336][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:45,148][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:45,148][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:46,509][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:46,519][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:47,790][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:47,800][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:49,403][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:49,403][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:50,587][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:50,597][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:51,901][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:51,901][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:53,741][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:53,741][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:55,487][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:55,497][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:57,070][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:57,070][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:28:58,958][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:28:58,974][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:00,906][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:00,906][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:02,168][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:02,168][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:03,364][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:03,374][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:04,786][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:04,786][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:06,806][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:06,816][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:08,650][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:08,650][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:10,002][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:10,002][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:12,003][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:12,003][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:13,437][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:13,447][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:15,263][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:15,273][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:16,682][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:16,682][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:18,289][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:18,289][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:20,236][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:20,236][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:21,924][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:21,935][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:23,402][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:23,412][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:24,810][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:24,810][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:26,350][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[WARN ][20161209 10:29:26,350][ClientCnxn$SendThread:1102] Session 0x158b9767d180086 for server null, unexpected error, closing socket connection and attempting reconnect
java.net.SocketException: Network is unreachable: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
[INFO ][20161209 10:29:27,762][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO ][20161209 10:29:27,783][ClientCnxn$SendThread:852] Socket connection established to 139.196.225.215/139.196.225.215:2181, initiating session
[INFO ][20161209 10:29:27,803][ZkClient:711] zookeeper state changed (Expired)
[INFO ][20161209 10:29:27,804][ClientCnxn$SendThread:1094] Unable to reconnect to ZooKeeper service, session 0x158b9767d180086 has expired, closing socket connection
[INFO ][20161209 10:29:27,804][ZooKeeper:438] Initiating client connection, connectString=139.196.225.215:2181 sessionTimeout=30000 watcher=org.I0Itec.zkclient.ZkClient@7a2e0858
[INFO ][20161209 10:29:27,808][ClientCnxn$EventThread:512] EventThread shut down
[INFO ][20161209 10:29:27,808][FailbackRegistry:282]  [DUBBO] Recover register url [dubbo://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626], dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 10:29:27,809][ClientCnxn$SendThread:975] Opening socket connection to server 139.196.225.215/139.196.225.215:2181. Will not attempt to authenticate using SASL (unknown error)
[INFO ][20161209 10:29:27,809][FailbackRegistry:292]  [DUBBO] Recover subscribe url [provider://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&category=configurators&check=false&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626], dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 10:29:27,832][ClientCnxn$SendThread:852] Socket connection established to 139.196.225.215/139.196.225.215:2181, initiating session
[INFO ][20161209 10:29:27,856][ClientCnxn$SendThread:1235] Session establishment complete on server 139.196.225.215/139.196.225.215:2181, sessionid = 0x158b9767d180093, negotiated timeout = 30000
[INFO ][20161209 10:29:27,856][ZkClient:711] zookeeper state changed (SyncConnected)
[INFO ][20161209 10:29:27,928][AbstractRegistry:422]  [DUBBO] Notify urls for subscribe url provider://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&category=configurators&check=false&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626, urls: [empty://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&category=configurators&check=false&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626], dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 10:29:28,586][FailbackRegistry:309]  [DUBBO] Retry register [dubbo://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626], dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 10:29:28,680][FailbackRegistry:354]  [DUBBO] Retry subscribe {provider://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&category=configurators&check=false&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626=[com.alibaba.dubbo.registry.integration.RegistryProtocol$OverrideListener@42fcc7e6]}, dubbo version: 2.5.3, current host: 127.0.0.1
[INFO ][20161209 10:29:28,877][AbstractRegistry:422]  [DUBBO] Notify urls for subscribe url provider://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&category=configurators&check=false&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626, urls: [empty://192.168.31.211:20882/com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade?anyhost=true&application=fengyu-service-crowd&category=configurators&check=false&dubbo=2.5.3&interface=com.fengyu.facade.crowdfunding.service.CrowdFundingEntityFacade&methods=submitCrowdFundingEntity,editCrowdFundingEntity,save,update,delete,findAll,getList4CrdFdBottomItem,editCrowdFundingEntityDetail,get,deleteByPK,newCrowdFundingEntity,deleteCrowdFundingEntity&pid=4176&side=provider&timestamp=1481200722626], dubbo version: 2.5.3, current host: 127.0.0.1
